apiVersion: v1
kind: Pod
metadata:
  name: cuda-test-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-container
    image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.6"
    resources:
      limits:
        nvidia.com/gpu: "1"